apiVersion: v1
kind: Service
metadata:
  name: satellite-sdn-controller
  labels:
    app: satellite-sdn-controller
spec:
  selector:
    app: satellite-sdn-controller
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
